<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>

<body>
  <h1>内存泄漏</h1>
  <p>在使用不当的情况下 闭包是会导致内存泄漏的 如果程序持续分配又不释放内存 就会导致运行速度越来越慢 , 设置崩溃 , 函数闭包之所以会导致内存泄漏 是因为闭包允许变量超出
    他们预期的声明周期而存在
  </p>
  <code>
    <pre>
      function createArrayAppender() {
      const arr = []
      return function appendTo(num) {
        arr.push(num)
      }
    }

    const appendToLargeArray = createArrayAppender()

    for (let i = 0; i < 1e8; i++) {
      appendToLargeArray(i)  //  RangeError: Invalid array length at Array.push(<anonymous>)
    }
    </pre>
  </code>
  <p>上面的例子中createArrayAppender函数返回了一个闭包 闭包引用了父作用域的变量arr 每次调用 appendTo 函数 都会像数组推人一个数值</p>
  <p>这段代码的问题在于变量arr 永远不会从内存中释放,即使闭包外面不再需要它。由于闭包维持着 , 对这个数组的引用，即使在createArrayAppender 数执行之后，数组也不会被当作垃圾回收
    。是，当我们在循环中调用appendroLargeArray时，就会不断向同一个数组中推人数值，导致数组在内存中越来越大 , 最终导致了抛出了错误 ,在一般情况也可以试试下面的方法
  </p>
  <code>
    <pre>
    function appendToTo(arr, num) {
      arr.push(num)
    }

    const largeArray = []
    for (let i = 0; i < 1e8; i++) {
      appendToTo(largeArray, i)
    }      
    </pre>
  </code>
  <p>即使已经没有使用闭包了 , 但是还是会因为数组太长了 , 而导致内存装不下了 最终还是会抛出错误</p>
  <script>
    // function createArrayAppender() {
    //   const arr = []
    //   return function appendTo(num) {
    //     arr.push(num)
    //   }
    // }

    // const appendToLargeArray = createArrayAppender()

    // for (let i = 0; i < 1e8; i++) {
    //   appendToLargeArray(i)  //  RangeError: Invalid array length at Array.push(<anonymous>)
    // }

    function appendToTo(arr, num) {
      arr.push(num)
    }

    const largeArray = []
    for (let i = 0; i < 1e8; i++) {
      appendToTo(largeArray, i)
    }
  </script>
</body>

</html>